modName = StorageBox
modId = storagebox
modGroup = com.github.tier940.storagebox
modVersion = 1.0.0
includeMCVersionJar = false
modArchivesBaseName = storagebox
autoUpdateBuildScript = false
minecraftVersion = 1.12.2
developmentEnvironmentUserName = Developer
additionalJavaArguments =
enableModernJavaSyntax = true
generateGradleTokenClass = com.github.tier940.storagebox.Tags
gradleTokenModId = MODID
gradleTokenModName = MODNAME
gradleTokenVersion = VERSION
apiPackage =
useSrcApiPath = false
accessTransformersFile =
usesMixins = true
mixinProviderSpec = zone.rong:mixinbooter:10.7
mixinsPackage = mixins
mixinConfigRefmap =
generateMixinConfig = false
coreModClass = core.StorageBoxCoreMod
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
enableCoreModDebug = false
includeWellKnownRepositories = true
includeCommonDevEnvMods = true
stripForgeRequirements = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
separateRunDirectories = false
versionDisplayFormat = $MOD_NAME − $VERSION
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
releaseType = release
generateDefaultChangelog = false
noPublishedSources = false
customMavenPublishUrl =
mavenArtifactGroup =
enableSpotless = true
enableJUnit = true
deploymentDebug = false
